### PR TITLE
Add web manifest and update icons

### PR DESCRIPTION
**Pull request by agneevX**
This PR:

- Adds a `manifest.json` file for Android Chrome PWA
- Updates the color of icons
- Adds a 96x96 image
- Moves all web assets to a separate directory

**`current`** | **`new`**
:-------------------------:|:-------------------------:
 | 

(If you have a better quality icon, I would be glad to change the current ones)

### CODE REVIEW

**Comment by mayswind** [comment]
One important feature of AriaNg is "multi-languages support", so I think it's necessary to process i18n even in manifest file. I'm afraid I cannot accept this pull request if i18n problem is not resolved.
In addition, I'm afraid I think manifest file cannot do much real useful work.

**Comment by agneevX** [comment]
Can you elaborate on this and maybe provide an outline of what has to be done?

> In addition, I'm afraid I think manifest file cannot do much real useful work.

It would help because the splash screen shows the web page title (`Download: 0.00 B/s`) and the PWA icon looks really tiny.

**Comment by mayswind** [comment]
You can modify page title in AriaNg setting page before you add icon to screen instead of using manifest.json file.

**Comment by agneevX** [comment]
Gotcha, but the app shortcuts are important too.

**Comment by mayswind** [comment]
1, I find some browser in android also uses "apple-touch-icon" as a shortcut icon, and AriaNg provides a 114*114 icon for it. So I don't have your problem.
2, Currently, the only way to modify AriaNg settings is to open the settings page and modify.

**Comment by agneevX** [comment]
> I find some browser in android also uses "apple-touch-icon" as a shortcut icon, and AriaNg provides a 114*114 icon for it. So I don't have your problem.

Webview does not. The current icon has rough edges and looks bad, I've updated the PR to reflect this.

**Comment by mayswind** [comment]
> > I find some browser in android also uses "apple-touch-icon" as a shortcut icon, and AriaNg provides a 114*114 icon for it. So I don't have your problem.
> 
> Webview does not. The current icon has rough edges and looks bad, I've updated the PR to reflect this.

I'm afraid I don't think your icon is better. If you like your icon, you can use your icon by yourself, but I cannot accept this pr.

**Comment by agneevX** [comment]
That's very unfortunate. I'm closing this.

**Pull request closed without merging**
