### PR TITLE
Build basic intelligence into default config

### PR DESCRIPTION
**Pull request by Haocen**

### CODE REVIEW

**Comment by mayswind** [comment]
Please check out existed function and code before submiting code. The default RPC host and protocol would be set to the same to AriaNg host automatically (ariaNgSettingService#initRpcSettingWithDefaultHostAndProtocol).

**Comment by Haocen** [comment]
@mayswind how about the default port? Setup in docker/secured environment usually has `nginx` or other reverse proxy that will reuse the existing port and redirect traffic to corresponding internal ports by detecting `/jsonrpc` in url path.

I do agree my code is not following proper structure and require amend.

**Comment by mayswind** [comment]
The default port of aria2 is 6800, and there are few people setting the rpc port to be the same as the http port.

**Comment by Haocen** [comment]
Yes I do understand that.

Please excuse me for my question, but how would user usually setup their `aria2` securely with SSL enabled? As far as I'm concerned serving the front end via https only is not providing any security benefits.

Given the context, if user has reverse proxy enabled and willing to take advantage of it, it would be routed via the same port that reverse proxy is listening to.

I might be looking out of the scope of this project, but it couldn't hurt to assume secured environment by default as https usage is growing rapidly nowadays.

**Comment by mayswind** [comment]
The purpose of AriaNg is to provide a general frontend for aria2. So the default settings of AriaNg should be the default settings of aria2, instead of any custom scenes of anyone.

**Pull request closed without merging**
