### PR TITLE
URI decode task name to show `download later` file names properly

### PR DESCRIPTION
**Pull request by kingofnull**
When I add new links as download later items task name became corrupted. You can see problem in following image:

image

I just fixed it by uridecode task name in template. I know it's not very elegant  but it worked and something is better than nothing.

Now its clean and readable :

image

### CODE REVIEW

**Comment by mayswind** [comment]
AriaNg would parse task name from url when the response data from aria2 does not have task name or downloaded path. I think its great to decode from the original url. But I think its more appropriate  to add your code after above-mentioned logic in the "getFileName" method in "aria2TaskService", and add "try-catch" segment to make your code more robustness.

**Comment by kingofnull** [comment]
> AriaNg would parse task name from url when the response data from aria2 does not have task name or downloaded path. I think its great to decode from the original url. But I think its more appropriate to add your code after above-mentioned logic in the "getFileName" method in "aria2TaskService", and add "try-catch" segment to make your code more robustness.

waiting list come directly from invokeAction and there is nothing between and no call to get file name. Also aria2 doesn't urlDecode file name until download get started.

Any way I added it to getFileName method and wrapped it in try  catch. And to working properly in waiting list I also ad map to run over all return items from getTaskList

I commit the changes please merge.

**Comment by mayswind** [comment]
@kingofnull 
You really should put your code in "getFileName" method in "aria2TaskService". But your code only processes the url which has query string...
I have pushed a commit (https://github.com/mayswind/AriaNg/commit/a31c0551670d16f19c59ea7b5b4576a49559399b) which implements this feature, and I would close this pr.

**Comment by kingofnull** [comment]
Dude your commit din't fix the problem in downloads waiting list! Why don't you get it?😭
image

Please consider this video (this the last release):


And this the URL and your can try it by yourself:
http://ml.servertwo.tk/E/Anime/2019/Fall/Beastars/720p/Beastars%2520-%252007%2520%255B720p%255D%2520%255BAnimDL.ir%255D.mkv

**Comment by mayswind** [comment]
@kingofnull
cuz the decoded url of "http://ml.servertwo.tk/E/Anime/2019/Fall/Beastars/720p/Beastars%2520-%252007%2520%255B720p%255D%2520%255BAnimDL.ir%255D.mkv" is "http://ml.servertwo.tk/E/Anime/2019/Fall/Beastars/720p/Beastars%20-%2007%20%5B720p%5D%20%5BAnimDL.ir%5D.mkv"

**Comment by kingofnull** [comment]
> @kingofnull
> cuz the decoded url of "http://ml.servertwo.tk/E/Anime/2019/Fall/Beastars/720p/Beastars%2520-%252007%2520%255B720p%255D%2520%255BAnimDL.ir%255D.mkv" is "http://ml.servertwo.tk/E/Anime/2019/Fall/Beastars/720p/Beastars%20-%2007%20%5B720p%5D%20%5BAnimDL.ir%5D.mkv"

You are right! Thanks.

**Pull request closed without merging**
